# Generated by Django 2.2.10 on 2020-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200502_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prior_high',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='prior_low',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='prior_medium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
